### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by shaikh-rashid**

### CODE REVIEW

**Comment by shaikh-rashid** [comment]
Does anyone know if the reason for the failing pytests?

**Comment by dashaylan** [comment]
> Does anyone know if the reason for the failing pytests?

Our code for evaluating DUO is pretty old now and that's probably why some of them are failing/may be causing the others not directly related to DUO to fail.

**Comment by shaikh-rashid** [comment]
@haoyuanli @ljdursi @dashaylan do we still intend to this datasets api?

**Comment by jimmyhli** [comment]
I'm not sure to be honest

**Comment by ljdursi** [comment]
We will need a datasets service further down the road; we can build on this one or start afresh.  It's not currently used.

**Review by ljdursi — APPROVED** [review]
LGTM

**Pull request merged**
